name: check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          pip install --upgrade -e .[dev]
      - name: Test
        run: |
          pytest --cov-report term-missing --cov itu.algs4
      - name: Lint
        run: |
          flake8 examples tests itu
          isort -c --diff examples tests itu
      - name: Typecheck
        run: |
          mypy
        continue-on-error: true
      - name: Documentation
        run: |
          pip install sphinx
          cd docs
          mkdir _target && mkdir _static
          sphinx-build . _target/
